### ISSUE TITLE
trouble with Ubuntu

### ISSUE THREAD

**Issue by kbuzzard** [leanprover-community/format_lean#3]
The default python on Ubuntu is 3.6. I can install 3.7 (or rather the worryingly-named `python3.7-minimal`) using `apt` but my `ipython` seems to use 3.6. Of course I can use python 3.7 by just typing `python3.7`. Here's a session:

```
format_lean/src$ python3.7
Python 3.7.1 (default, Oct 22 2018, 11:21:55) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from format_lean.lecture import render_lean_file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/buzzard/Encfs/Computer_languages/python/format_lean/src/format_lean/lecture.py", line 7, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/buzzard/Encfs/Computer_languages/python/format_lean/src/format_lean/lecture.py", line 7, in <module>
    import regex
ModuleNotFoundError: No module named 'regex'
>>> 
```

I have never used `pip3` before, but I have it installed. 

I suspect that the problem is that python3.7 is not being used globally. However I can't get the instructions on how to move to a 3.7 environment to work either. `pip3 install --user virtualenvwrapper` works fine, `export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv` looks fishy to me because the only `virtualenv` I can find on my system is in `/usr/bin/`, but replacing `/usr/local/bin` with `/usr/bin` and continuing gives me

```
$ source $HOME/.local/bin/virtualenvwrapper.sh
/usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks.

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.
```

and /usr/bin/python is still Python 2.7 on Ubuntu.

**Comment by kbuzzard** [comment]
Some progress: I figured out (I think) how to create a virtual environment for Python 3.7 but because I have no understanding of what's going on I don't know what order to do things in. My prompt is

```
(py37-venv) buzzard@bob: [stuff]/format_lean$
```
which looks good, `python` and `python3` both give me 3.7.1, `pip3 install .` gives me

```
Processing /home/buzzard/Encfs/Computer_languages/python/format_lean
Requirement already satisfied: jinja2>=2.10 in /home/buzzard/py37-venv/lib/python3.7/site-packages (from Lean-formatter==0.0.1)
Collecting regex>=2018.7.11 (from Lean-formatter==0.0.1)
  Using cached https://files.pythonhosted.org/packages/8e/2d/812284cdc6376ce49f6a434ca70229c285ffca672040434d2221654c62ce/regex-2019.02.07.tar.gz
Requirement already satisfied: MarkupSafe>=0.23 in /home/buzzard/py37-venv/lib/python3.7/site-packages (from jinja2>=2.10->Lean-formatter==0.0.1)
Building wheels for collected packages: regex
  Running setup.py bdist_wheel for regex ... error
  Complete output from command /home/buzzard/py37-venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p_dsoqs6/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppninnpbvpip-wheel- --python-tag cp37:
  /home/buzzard/py37-venv/lib/python3.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '2019.02.07' to '2019.2.7'
    normalized_version,
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for regex
  Running setup.py clean for regex
Failed to build regex
Installing collected packages: regex, Lean-formatter
  Running setup.py install for regex ... error
    Complete output from command /home/buzzard/py37-venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p_dsoqs6/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xcu4zrag-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/buzzard/py37-venv/include/site/python3.7/regex:
    /home/buzzard/py37-venv/lib/python3.7/site-packages/setuptools/dist.py:397: UserWarning: Normalizing '2019.02.07' to '2019.2.7'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    copying regex_3/regex.py -> build/lib.linux-x86_64-3.7
    copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.7
    copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.7
    running build_ext
    building '_regex' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/regex_3
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/buzzard/py37-venv/include -I/usr/include/python3.7m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.7/regex_3/_regex.o
    regex_3/_regex.c:48:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/buzzard/py37-venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p_dsoqs6/regex/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xcu4zrag-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/buzzard/py37-venv/include/site/python3.7/regex" failed with error code 1 in /tmp/pip-build-p_dsoqs6/regex/
```
although `pip3 install ipython` works and gives me an ipython with 3.7, so I seem to be getting somewhere.

**Comment by kbuzzard** [comment]
Hmm. I had not installed package `python3.7-dev`.

**Comment by kbuzzard** [comment]
OK. Installation instructions for Ubuntu 18.04 for those who know nothing about python environments (the issue is that Ubuntu 18.04 ships with Python 2.7 and 3.6 which already makes life complicated enough): 

1) I installed packages `python3.7` and `python3.7-dev` [the latter is essential and missing it was what caused the problems above] and `python3.7-venv`. 
2) I created a new environment [which creates a new directory `py37-venv`] with `$ python3.7 -m venv py37-venv` and activated it with `. py37-venv/bin/activate`. My prompt now has `(py37-venv)` in front of it. Note that I couldn't get Patrick's instructions on how to do this to work.
3) In the virtual environment you can do `pip3 install ipython` to get `ipython` working with python 3.7.
4) Now change directory to `format_lean` and `pip3 install .` should work.
5) Now change directory to `format_lean/src` and fire up `ipython`; now `from format_lean.lecture import render_lean_file` should work too.

Unfortunately I can't guarantee this works with vanilla Ubuntu out of the box because I will have had a bunch of other stuff installed already.
